### ISSUE TITLE
not detecting GPU

### ISSUE THREAD

**Issue by ekospirit** [SecureAI-Tools/SecureAI-Tools#103]
I have gotten the compose indentation correct, when I check the logs inside the container I get this response

```
time=2024-04-15T15:48:34.593Z level=INFO source=images.go:804 msg="total blobs: 5"
time=2024-04-15T15:48:34.593Z level=INFO source=images.go:811 msg="total unused blobs removed: 0"
time=2024-04-15T15:48:34.594Z level=INFO source=routes.go:1118 msg="Listening on [::]:11434 (version 0.1.31)"
time=2024-04-15T15:48:34.594Z level=INFO source=payload_common.go:113 msg="Extracting dynamic libraries to /tmp/ollama913939083/runners ..."
time=2024-04-15T15:48:38.322Z level=INFO source=payload_common.go:140 msg="Dynamic LLM libraries [cpu cuda_v11 cpu_avx rocm_v60000 cpu_avx2]"
time=2024-04-15T15:48:38.322Z level=INFO source=gpu.go:115 msg="Detecting GPU type"
time=2024-04-15T15:48:38.322Z level=INFO source=gpu.go:265 msg="Searching for GPU management library libcudart.so*"
time=2024-04-15T15:48:38.323Z level=INFO source=gpu.go:311 msg="Discovered GPU libraries: [/tmp/ollama913939083/runners/cuda_v11/libcudart.so.11.0]"
time=2024-04-15T15:48:38.325Z level=INFO source=gpu.go:340 msg="Unable to load cudart CUDA management library /tmp/ollama913939083/runners/cuda_v11/libcudart.so.11.0: cudart init failure: 100"
time=2024-04-15T15:48:38.325Z level=INFO source=gpu.go:265 msg="Searching for GPU management library libnvidia-ml.so"
time=2024-04-15T15:48:38.326Z level=INFO source=gpu.go:311 msg="Discovered GPU libraries: [/usr/lib/x86_64-linux-gnu/libnvidia-ml.so.550.54.14]"
time=2024-04-15T15:48:38.335Z level=INFO source=gpu.go:323 msg="Unable to load NVML management library /usr/lib/x86_64-linux-gnu/libnvidia-ml.so.550.54.14: nvml vram init failure: 999"
time=2024-04-15T15:48:38.335Z level=INFO source=cpu_common.go:11 msg="CPU has AVX2"
time=2024-04-15T15:48:38.335Z level=INFO source=routes.go:1141 msg="no GPU detected"

```

Now, my system has this
```

+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.14              Driver Version: 550.54.14      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce GTX 1070        Off |   00000000:01:00.0 Off |                  N/A |
| 33%   32C    P8             11W /  151W |       2MiB /   8192MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|  No running processes found                                                             |
+-----------------------------------------------------------------------------------------+

nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2023 NVIDIA Corporation
Built on Fri_Jan__6_16:45:21_PST_2023
Cuda compilation tools, release 12.0, V12.0.140
Build cuda_12.0.r12.0/compiler.32267302_0

```

Is there something I'm missing/doing wrong here? been scratching my head trying to figure out what I am missing, 12.4 is backwards compatible with 11.0 so that shouldn't be an issue

**Comment by ekospirit** [comment]
I found the solution,

in the "/etc/nvidia-container-runtime/config.toml"

you need to change parameter to false
no-cgroups = false

or you have to run the inference container as privileged
